version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      pip-non-major:
        update-types:
          - minor
          - patch
      pip-major:
        update-types:
          - major
    labels:
      - "type:dependencies"
    open-pull-requests-limit: 2

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      npm-non-major:
        update-types:
          - minor
          - patch
      npm-major:
        update-types:
          - major
    labels:
      - "type:dependencies"
    open-pull-requests-limit: 2

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels:
      - "type:dependencies"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - "type:dependencies"
